# Generated by Django 6.0.8 on 2026-08-04 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('secteur', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('pays', models.CharField(default='Togo', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('poids', models.DecimalField(decimal_places=2, default=0.2, help_text='Poids de la dimension dans le score global (ex. 0.20 pour 20%).', max_digits=4)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Formulaire A - Fiche Administration'), ('B', 'Formulaire B - Enquête individuelle agent')], max_length=1, unique=True)),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TypeChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150)),
                ('service', models.CharField(blank=True, max_length=150)),
                ('tranche_age', models.CharField(blank=True, choices=[('<30', 'Moins de 30 ans'), ('30-45', '30-45 ans'), ('45-55', '45-55 ans'), ('>55', 'Plus de 55 ans')], max_length=10)),
                ('anciennete', models.CharField(blank=True, max_length=20)),
                ('niveau_etudes', models.CharField(blank=True, max_length=100)),
                ('mode_saisie', models.CharField(choices=[('autonome', 'Autonome'), ('assiste', 'Assisté par un enquêteur')], default='autonome', max_length=20)),
                ('niveau_maturite', models.PositiveSmallIntegerField(blank=True, help_text='Niveau calculé de 0 (jamais utilisé un ordinateur) à 5', null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.administration')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. 1.1, B2.1, B3.4', max_length=10)),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('aide', models.CharField(blank=True, help_text="Texte d'aide contextuelle (icône ⓘ)", max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('valeur_condition', models.CharField(blank=True, max_length=100)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.dimension')),
                ('question_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_dependantes', to='core.question')),
                ('type_champ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typechamp')),
            ],
            options={
                'ordering': ['dimension__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('valeur', models.CharField(help_text='Valeur technique utilisée pour le scoring', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('administration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.administration')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.agent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.question')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reponse'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent_evaluateur', 'Agent évaluateur'), ('agent_enquete', 'Agent enquêté'), ('enqueteur', 'Enquêteur'), ('dsi_decideur', 'DSI / Décideur'), ('admin_contenu', 'Administrateur de contenu')], max_length=30)),
                ('administration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.administration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.formulaire')),
            ],
            options={
                'ordering': ['-numero_version'],
                'unique_together': {('formulaire', 'numero_version')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='version_formulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.versionformulaire'),
        ),
    ]
