# Generated by Django 5.2.17 on 2026-08-29 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('administration', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(choices=[('rejoindre', 'Rejoindre la démarche'), ('demonstration', 'Demander une démonstration'), ('question', 'Poser une question')], default='question', max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RegleRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_code', models.SlugField(max_length=30)),
                ('seuil_max', models.DecimalField(decimal_places=1, help_text='Règle appliquée si le score de la dimension est ≤ ce seuil (sur 5).', max_digits=3)),
                ('priorite', models.CharField(choices=[('P1', 'P1 — critique'), ('P2', 'P2 — important'), ('P3', 'P3 — à planifier')], max_length=2)),
                ('texte', models.CharField(max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Règle de recommandation',
                'verbose_name_plural': 'Règles de recommandation',
                'ordering': ['priorite', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='email_accuse',
            field=models.EmailField(blank=True, help_text="E-mail optionnel pour l'accusé, non relié aux réponses.", max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='enqueteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_menees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro séquentiel de l'agent dans l'évaluation (ex. 037).", null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='progression',
            field=models.PositiveIntegerField(default=0, help_text="Index de la dernière question répondue (reprise d'enquête)."),
        ),
        migrations.AddField(
            model_name='agent',
            name='reference',
            field=models.CharField(blank=True, help_text='Accusé de participation (ex. MN-2026-000372).', max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_faire', max_length=10),
        ),
        migrations.AddField(
            model_name='dimension',
            name='code',
            field=models.SlugField(blank=True, help_text='Identifiant stable : infra, services, competences, juridique, engagement.', max_length=30),
        ),
        migrations.AddField(
            model_name='dimension',
            name='couleur',
            field=models.CharField(default='#3E90F0', help_text='Couleur hex pour le radar et les pastilles (ex. #3E90F0).', max_length=7),
        ),
        migrations.AddField(
            model_name='dimension',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom d'icône Lucide.", max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='borne_max_label',
            field=models.CharField(blank=True, help_text='Libellé de la borne haute (ex. « Excellente »).', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='borne_min_label',
            field=models.CharField(blank=True, help_text='Libellé de la borne basse (ex. « Aucune »).', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='obligatoire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, help_text='Section du Formulaire B : administration, profil, bases, usage, freins.', max_length=30),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('archivee', 'Archivée')], default='brouillon', max_length=15)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('responsable_nom', models.CharField(blank=True, help_text='Ex. « Chef de service informatique ».', max_length=150)),
                ('reference', models.CharField(blank=True, help_text='Identifiant du rapport, ex. MN-2026-000372.', max_length=30, null=True, unique=True)),
                ('score_global', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_par_dimension', models.JSONField(blank=True, default=dict)),
                ('distribution_niveaux', models.JSONField(blank=True, default=dict)),
                ('niveau_libelle', models.CharField(blank=True, max_length=50)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.administration')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
                ('version_formulaire_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_formulaire_a', to='core.versionformulaire')),
                ('version_formulaire_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_formulaire_b', to='core.versionformulaire')),
            ],
            options={
                'ordering': ['-date_ouverture', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.evaluation'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.evaluation'),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.CharField(choices=[('P1', 'P1 — critique'), ('P2', 'P2 — important'), ('P3', 'P3 — à planifier')], max_length=2)),
                ('texte', models.CharField(max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations', to='core.dimension')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='core.evaluation')),
            ],
            options={
                'ordering': ['priorite', 'ordre'],
            },
        ),
    ]
