# Generated by Django 5.2.17 on 2026-08-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagecontact_reglerecommandation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('agent_evaluateur', 'Agent évaluateur'), ('enqueteur', 'Enquêteur'), ('dsi_decideur', 'DSI / Décideur'), ('admin_contenu', 'Administrateur de contenu')], max_length=30),
        ),
    ]
