# Generated by Django 5.2.17 on 2026-08-29 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Jeton d'accès au brouillon d'enquête (reprise sans compte)."),
        ),
    ]
