# Generated by Django 5.2.17 on 2026-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='nom',
            field=models.CharField(blank=True, help_text="Nom et prénom de l'agent (B1.0).", max_length=150),
        ),
    ]
