# Generated by Django 5.2.17 on 2026-08-30 10:49

from django.conf import settings
from django.db import migrations, models


def rattacher_enqueteurs_existants(apps, schema_editor):
    """Reprend l'affectation historique : chaque enquêteur rattaché à une
    administration via `Utilisateur.administration` est ajouté à sa liste
    d'enquêteurs (M2M), pour ne rien casser après le passage au multi-admin."""
    Utilisateur = apps.get_model('core', 'Utilisateur')
    for profil in Utilisateur.objects.filter(role='enqueteur').exclude(administration__isnull=True):
        profil.administration.enqueteurs.add(profil.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agent_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='enqueteurs',
            field=models.ManyToManyField(blank=True, help_text="Comptes enquêteurs autorisés à mener l'enquête agents dans cette administration.", limit_choices_to={'profil__role': 'enqueteur'}, related_name='administrations_enquetees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(rattacher_enqueteurs_existants, migrations.RunPython.noop),
    ]
