# Generated by Django 5.2.17 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_desactiver_question_b1_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prenom',
            field=models.CharField(blank=True, help_text="Prénom(s) de l'agent (B1.0b).", max_length=150),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nom',
            field=models.CharField(blank=True, help_text="Nom de famille de l'agent (B1.0).", max_length=150),
        ),
    ]
