# Generated by Django 5.2.17 on 2026-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agent_prenom_messagecontact_prenom_alter_agent_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='anciennete',
            field=models.CharField(blank=True, choices=[('<5', 'Moins de 5 ans'), ('5-15', '5 à 15 ans'), ('>15', 'Plus de 15 ans')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='niveau_etudes',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun diplôme'), ('primaire', 'Primaire'), ('college', 'Collège / BEPC'), ('bac', 'Baccalauréat'), ('superieur', 'Études supérieures')], max_length=100),
        ),
    ]
