from django.urls import path

from .views import (
    acces_par_role,
    administration_detail,
    backoffice,
    conditions,
    confidentialite,
    contact,
    dashboard,
    demarche,
    dimensions_publiques,
    enqueteur_home,
    formulaire_a,
    formulaire_a_etape,
    formulaire_a_fin,
    formulaire_b,
    formulaire_b_public,
    home,
    login_view,
    logout_view,
    profile,
    roles,
)

urlpatterns = [
    path('', home, name='home'),
    path('demarche/', demarche, name='demarche'),
    path('dimensions/', dimensions_publiques, name='dimensions_publiques'),
    path('acces-par-role/', acces_par_role, name='acces_par_role'),
    path('contact/', contact, name='contact'),
    path('confidentialite/', confidentialite, name='confidentialite'),
    path('conditions-utilisation/', conditions, name='conditions'),
    path('connexion/', login_view, name='connexion'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('back-office/', backoffice, name='backoffice'),
    path('enquetes/', enqueteur_home, name='enqueteur_home'),
    path('administration/<int:administration_id>/', administration_detail, name='administration_detail'),
    path('formulaire-a/', formulaire_a, name='formulaire_a'),
    path('formulaire-a/etape/<int:numero>/', formulaire_a_etape, name='formulaire_a_etape'),
    path('formulaire-a/termine/', formulaire_a_fin, name='formulaire_a_fin'),
    path('formulaire-b/', formulaire_b, name='formulaire_b'),
    path('agent-enquete/', formulaire_b_public, name='formulaire_b_public'),
    path('profile/', profile, name='profile'),
    path('roles/', roles, name='roles'),
]
