from django.urls import path

from .views import (
    acces_par_role,
    administration_resultats,
    administrations_liste,
    backoffice,
    bo_dimension_form,
    bo_dimension_ordre,
    bo_question_form,
    bo_question_ordre,
    bo_questions,
    bo_questions_index,
    bo_versions,
    comparaison,
    conditions,
    confidentialite,
    contact,
    dashboard,
    demarche,
    dimensions_publiques,
    enquete_confirmation,
    enquete_demarrer,
    enquete_envoi,
    enquete_intro,
    enquete_section,
    enqueteur_agent_voir,
    enqueteur_home,
    enqueteur_nouvel_agent,
    formulaire_a,
    formulaire_a_etape,
    formulaire_a_fin,
    formulaire_b,
    formulaire_b_assiste,
    home,
    login_view,
    logout_view,
    profile,
    rapport_administration,
    rapports,
    roles,
)

urlpatterns = [
    path('', home, name='home'),
    path('demarche/', demarche, name='demarche'),
    path('dimensions/', dimensions_publiques, name='dimensions_publiques'),
    path('acces-par-role/', acces_par_role, name='acces_par_role'),
    path('contact/', contact, name='contact'),
    path('confidentialite/', confidentialite, name='confidentialite'),
    path('conditions-utilisation/', conditions, name='conditions'),
    path('connexion/', login_view, name='connexion'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('tableau-de-bord/', dashboard, name='dashboard'),
    path('administrations/', administrations_liste, name='administrations'),
    path('administrations/<int:administration_id>/', administration_resultats, name='administration_resultats'),
    path('administrations/<int:administration_id>/rapport/', rapport_administration, name='rapport_administration'),
    path('comparaison/', comparaison, name='comparaison'),
    path('rapports/', rapports, name='rapports'),
    path('back-office/', backoffice, name='backoffice'),
    path('back-office/dimensions/nouvelle/', bo_dimension_form, name='bo_dimension_nouvelle'),
    path('back-office/dimensions/<int:dimension_id>/editer/', bo_dimension_form, name='bo_dimension_editer'),
    path('back-office/dimensions/<int:dimension_id>/ordre/<str:sens>/', bo_dimension_ordre, name='bo_dimension_ordre'),
    path('back-office/dimensions/<int:dimension_id>/questions/', bo_questions, name='bo_questions'),
    path(
        'back-office/dimensions/<int:dimension_id>/questions/nouvelle/',
        bo_question_form, name='bo_question_nouvelle',
    ),
    path('back-office/questions/', bo_questions_index, name='bo_questions_index'),
    path('back-office/questions/<int:question_id>/editer/', bo_question_form, name='bo_question_editer'),
    path('back-office/questions/<int:question_id>/ordre/<str:sens>/', bo_question_ordre, name='bo_question_ordre'),
    path('back-office/versions/', bo_versions, name='bo_versions'),
    path('enquetes/', enqueteur_home, name='enqueteur_home'),
    path('enquetes/nouvel-agent/', enqueteur_nouvel_agent, name='enqueteur_nouvel_agent'),
    path('enquetes/agent/<int:agent_id>/', enqueteur_agent_voir, name='enqueteur_agent_voir'),
    path('enquetes/agent/<int:agent_id>/question/<int:index>/', formulaire_b_assiste, name='formulaire_b_assiste'),
    path('formulaire-a/', formulaire_a, name='formulaire_a'),
    path('formulaire-a/etape/<int:numero>/', formulaire_a_etape, name='formulaire_a_etape'),
    path('formulaire-a/termine/', formulaire_a_fin, name='formulaire_a_fin'),
    path('formulaire-b/', formulaire_b, name='formulaire_b'),
    path('enquete/', enquete_intro, name='enquete_intro'),
    path('agent-enquete/', enquete_intro, name='formulaire_b_public'),
    path('enquete/demarrer/', enquete_demarrer, name='enquete_demarrer'),
    path('enquete/<uuid:token>/section/<slug:section>/', enquete_section, name='enquete_section'),
    path('enquete/<uuid:token>/envoi/', enquete_envoi, name='enquete_envoi'),
    path('enquete/<uuid:token>/confirmation/', enquete_confirmation, name='enquete_confirmation'),
    path('profile/', profile, name='profile'),
    path('roles/', roles, name='roles'),
]
